// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGr_nI8rGVrPd9GKF6Jwd3HtELMzfsB78',
    appId: '1:421591206384:web:90064ef28c2b91a50fb535',
    messagingSenderId: '421591206384',
    projectId: 'the-newz-e5101',
    authDomain: 'the-newz-e5101.firebaseapp.com',
    storageBucket: 'the-newz-e5101.appspot.com',
    measurementId: 'G-VB11H3BDGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdh66h1BD3H8qcKi4-FizD2xrZkJwuAH8',
    appId: '1:421591206384:android:d375698b8d21ea090fb535',
    messagingSenderId: '421591206384',
    projectId: 'the-newz-e5101',
    storageBucket: 'the-newz-e5101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3XydACOTx0X9Ov0f-mxoxxkLnFNoG9_E',
    appId: '1:421591206384:ios:a734a8695138ccf50fb535',
    messagingSenderId: '421591206384',
    projectId: 'the-newz-e5101',
    storageBucket: 'the-newz-e5101.appspot.com',
    androidClientId: '421591206384-akic0n51v3e5m2bi0csla2eievkgjufo.apps.googleusercontent.com',
    iosClientId: '421591206384-ve3kdq8rl51f6i7pcq4oac6k5p0sehh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.theNewz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3XydACOTx0X9Ov0f-mxoxxkLnFNoG9_E',
    appId: '1:421591206384:ios:a734a8695138ccf50fb535',
    messagingSenderId: '421591206384',
    projectId: 'the-newz-e5101',
    storageBucket: 'the-newz-e5101.appspot.com',
    androidClientId: '421591206384-akic0n51v3e5m2bi0csla2eievkgjufo.apps.googleusercontent.com',
    iosClientId: '421591206384-ve3kdq8rl51f6i7pcq4oac6k5p0sehh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.theNewz',
  );
}
